title: "Rebecca Byrnes — Cybersecurity & Compliance"
description: "Cybersecurity, Information Security Compliance (ISO 27001, SOC 2), based in Portugal"
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

